Make the subparser command required
This makes argparse handle automatically the case where the
(sub-)command is omitted.  For example, using just "toutv" would show
the help, but using "toutv --verbose" would result in an exception:

Traceback (most recent call last):
  File "/home/simark/src/pytoutv-env/bin/toutv", line 9, in <module>
    load_entry_point('pytoutv==2.3.1', 'console_scripts', 'toutv')()
  File "/home/simark/src/pytoutv/toutvcli/app.py", line 672, in run
    return app.run()
  File "/home/simark/src/pytoutv/toutvcli/app.py", line 91, in run
    if args.build_client:
AttributeError: 'Namespace' object has no attribute 'build_client'

As a result, we don't return the exit code 10 when bad arguments are
given.

Signed-off-by: Simon Marchi <simon.marchi@polymtl.ca>